// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7-MYXGNG0ICrGun5_ePyKLo-vtfgjTAo',
    appId: '1:450720717923:web:0781ae54eb7a3087c9ac56',
    messagingSenderId: '450720717923',
    projectId: 'imsm-541de',
    authDomain: 'imsm-541de.firebaseapp.com',
    storageBucket: 'imsm-541de.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-sMYR5hJbv67aY8lt3_BKIOiRy_WRfhQ',
    appId: '1:450720717923:android:dcbce70e86a18b09c9ac56',
    messagingSenderId: '450720717923',
    projectId: 'imsm-541de',
    storageBucket: 'imsm-541de.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoTLwXWdOKYEiGGDbbjRKRWhmM34Rb-SM',
    appId: '1:450720717923:ios:c69541714a163842c9ac56',
    messagingSenderId: '450720717923',
    projectId: 'imsm-541de',
    storageBucket: 'imsm-541de.appspot.com',
    iosBundleId: 'com.example.ims',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoTLwXWdOKYEiGGDbbjRKRWhmM34Rb-SM',
    appId: '1:450720717923:ios:6f977eef348c86d1c9ac56',
    messagingSenderId: '450720717923',
    projectId: 'imsm-541de',
    storageBucket: 'imsm-541de.appspot.com',
    iosBundleId: 'com.example.ims.RunnerTests',
  );
}
